//
// Generated file, do not edit! Created by nedtool 5.4 from node/Packet.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PACKET_M_H
#define __PACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



class Packet;
/**
 * Class generated from <tt>node/Packet.msg:15</tt> by nedtool.
 * <pre>
 * //
 * // Represents a packet in the network.
 * //
 * packet Packet
 * {
 *     int srcAddr \@packetData;
 *     int destAddr \@packetData;
 *     int hopCount \@packetData;
 * 
 *     // This is an enum and it has the following meaning
 *     // 0 - Transaction  
 *     // 1 - Chain Request
 *     // 2 - Send Chain
 *     // 3 - Ack of Transaction
 *     int packetType \@packetData;
 * 
 *     //Send Transaction
 *     int transactionValue \@packetData;
 * 
 *     //Sending Chain Information
 *     int databaseSize \@packetData;
 *     int userA[] \@packetData;
 *     int userB[] \@packetData;
 *     int transaction[] \@packetData;
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cPacket
{
  protected:
    int srcAddr = 0;
    int destAddr = 0;
    int hopCount = 0;
    int packetType = 0;
    int transactionValue = 0;
    int databaseSize = 0;
    int *userA = nullptr;
    size_t userA_arraysize = 0;
    int *userB = nullptr;
    size_t userB_arraysize = 0;
    int *transaction = nullptr;
    size_t transaction_arraysize = 0;

  private:
    void copy(const Packet& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Packet&);

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSrcAddr() const;
    virtual void setSrcAddr(int srcAddr);
    virtual int getDestAddr() const;
    virtual void setDestAddr(int destAddr);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual int getPacketType() const;
    virtual void setPacketType(int packetType);
    virtual int getTransactionValue() const;
    virtual void setTransactionValue(int transactionValue);
    virtual int getDatabaseSize() const;
    virtual void setDatabaseSize(int databaseSize);
    virtual void setUserAArraySize(size_t size);
    virtual size_t getUserAArraySize() const;
    virtual int getUserA(size_t k) const;
    virtual void setUserA(size_t k, int userA);
    virtual void insertUserA(int userA);
    virtual void insertUserA(size_t k, int userA);
    virtual void eraseUserA(size_t k);
    virtual void setUserBArraySize(size_t size);
    virtual size_t getUserBArraySize() const;
    virtual int getUserB(size_t k) const;
    virtual void setUserB(size_t k, int userB);
    virtual void insertUserB(int userB);
    virtual void insertUserB(size_t k, int userB);
    virtual void eraseUserB(size_t k);
    virtual void setTransactionArraySize(size_t size);
    virtual size_t getTransactionArraySize() const;
    virtual int getTransaction(size_t k) const;
    virtual void setTransaction(size_t k, int transaction);
    virtual void insertTransaction(int transaction);
    virtual void insertTransaction(size_t k, int transaction);
    virtual void eraseTransaction(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}

#endif // ifndef __PACKET_M_H

