#!/bin/bash
#SBATCH --time=00:60:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=8

. /etc/bashrc
. /etc/profile.d/modules.sh
module load openmpi/gcc/64

cd omnetpp-5.5.1/samples/Simulation1

./Simulation1 -r '0.. 99' -m -u Cmdenv omnetpp.ini  > ../../../result/$1


#opp_runall -j24 -V ./Simulation1 -u Cmdenv -c General -r '0..3' omnetpp.ini  > ../../../result/$1Log
#cd results
#cat General-#* > ../../../../result/$1
